"""add created_at to scans

Revision ID: 6715084468e9
Revises: ead3c4176891
Create Date: 2026-08-29 19:05:05.598777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6715084468e9'
down_revision: Union[str, Sequence[str], None] = 'ead3c4176891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_column('scans', 'created_at')
    # ### end Alembic commands ###
