"""add risk assessment to scans

Revision ID: 820a31008900
Revises: a763fe0c6169
Create Date: 2026-08-23 16:41:27.894997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820a31008900'
down_revision: Union[str, Sequence[str], None] = 'a763fe0c6169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('risk_grade', sa.String(length=1), nullable=True))
    op.add_column('scans', sa.Column('risk_level', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'risk_level')
    op.drop_column('scans', 'risk_grade')
    op.drop_column('scans', 'risk_score')
    # ### end Alembic commands ###
