"""
Centralized permission model for enterprise multi-tenancy + RBAC (P14.2).

Roles are separated:
- Platform: super_admin
- Organization: organization_admin, security_admin, security_analyst, developer, viewer, auditor (+ legacy member/org_admin)
- Project: project_admin, security_analyst, developer, viewer, auditor (+ legacy analyst/viewer)

Permissions are the authoritative check; roles map to permission sets.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Role definitions
# ---------------------------------------------------------------------------

PLATFORM_ROLES = {"super_admin"}
# Enterprise org roles + legacy aliases
ORG_ROLES = {"organization_admin", "security_admin", "security_analyst", "developer", "viewer", "auditor", "member", "org_admin"}
PROJECT_ROLES = {"project_admin", "security_admin", "security_analyst", "developer", "viewer", "auditor", "analyst"}

# Aliases for backward compat: map legacy to canonical
ORG_ROLE_ALIASES = {"member": "viewer", "org_admin": "organization_admin"}
PROJECT_ROLE_ALIASES = {"analyst": "security_analyst"}

def canonical_org_role(role: str) -> str:
    return ORG_ROLE_ALIASES.get(role, role)

def canonical_project_role(role: str) -> str:
    return PROJECT_ROLE_ALIASES.get(role, role)

# ---------------------------------------------------------------------------
# Permission vocabulary (P14.2) — deterministic, documented
# ---------------------------------------------------------------------------

# Projects
PERM_PROJECT_READ = "projects.read"
PERM_PROJECT_CREATE = "projects.create"
PERM_PROJECT_UPDATE = "projects.update"
PERM_PROJECT_DELETE = "projects.delete"
PERM_PROJECT_MANAGE_MEMBERS = "project.manage_members"

# Targets
PERM_TARGET_READ = "targets.read"
PERM_TARGET_CREATE = "targets.create"
PERM_TARGET_UPDATE = "targets.update"
PERM_TARGET_DELETE = "targets.delete"

# Scans
PERM_SCAN_READ = "scans.read"
PERM_SCAN_CREATE = "scans.create"
PERM_SCAN_CANCEL = "scans.cancel"
PERM_SCAN_DELETE = "scans.delete"

# Findings
PERM_FINDING_READ = "findings.read"
PERM_FINDING_TRIAGE = "findings.triage"
PERM_FINDING_ASSIGN = "findings.assign"
PERM_FINDING_UPDATE = "findings.update"
PERM_FINDING_ACCEPT_RISK = "findings.accept_risk"
PERM_FINDING_CLOSE = "findings.close"
PERM_FINDING_REOPEN = "findings.reopen"

# Assets
PERM_ASSET_READ = "assets.read"
PERM_ASSET_UPDATE = "assets.update"

# Attack Surface
PERM_ATTACK_SURFACE_READ = "attack_surface.read"

# Continuous Monitoring
PERM_MONITORING_READ = "monitoring.read"
PERM_MONITORING_MANAGE = "monitoring.manage"

# Reports
PERM_REPORT_READ = "reports.read"
PERM_REPORT_CREATE = "reports.create"
PERM_REPORT_DELETE = "reports.delete"

# Compliance
PERM_COMPLIANCE_READ = "compliance.read"
PERM_COMPLIANCE_MANAGE = "compliance.manage"

# Code Security
PERM_CODE_SECURITY_READ = "code_security.read"
PERM_CODE_SECURITY_MANAGE = "code_security.manage"

# Cloud Security
PERM_CLOUD_READ = "cloud.read"
PERM_CLOUD_MANAGE = "cloud.manage"
PERM_CLOUD_SECURITY_READ = "cloud_security.read"
PERM_CLOUD_SECURITY_MANAGE = "cloud_security.manage"

# DAST/API
PERM_DAST_READ = "dast.read"
PERM_DAST_MANAGE = "dast.manage"

# Repositories
PERM_REPO_READ = "repositories.read"
PERM_REPO_CONNECT = "repositories.connect"
PERM_REPO_MANAGE = "repositories.manage"

# Integrations
PERM_INTEGRATION_READ = "integrations.read"
PERM_INTEGRATION_MANAGE = "integrations.manage"

# Cloud Accounts
PERM_CLOUD_ACCOUNT_READ = "cloud_accounts.read"
PERM_CLOUD_ACCOUNT_CONNECT = "cloud_accounts.connect"
PERM_CLOUD_ACCOUNT_MANAGE = "cloud_accounts.manage"

# External Attack Surface (E15)
PERM_EXTERNAL_SCOPE_READ = "external_scope.read"
PERM_EXTERNAL_SCOPE_WRITE = "external_scope.write"
PERM_EXTERNAL_SCOPE_ENTRY_READ = "external_scope.entry.read"
PERM_EXTERNAL_SCOPE_ENTRY_WRITE = "external_scope.entry.write"
PERM_EXTERNAL_DISCOVERY_READ = "external_discovery.read"
PERM_EXTERNAL_DISCOVERY_RUN = "external_discovery.run"
PERM_EXTERNAL_ASSET_READ = "external_asset.read"
PERM_EXTERNAL_ASSET_REVIEW = "external_asset.review"
PERM_EXTERNAL_ASSET_AUTHORIZE = "external_asset.authorize"
PERM_EXTERNAL_ASSET_REJECT = "external_asset.reject"

# Application Security Intelligence (E16)
PERM_APPLICATION_READ = "application.read"
PERM_APPLICATION_WRITE = "application.write"
PERM_APPLICATION_ASSET_LINK = "application.asset.link"
PERM_APPLICATION_FINDING_READ = "application.finding.read"
PERM_APPLICATION_INVESTIGATION_CREATE = "application.investigation.create"
PERM_APPLICATION_OWNER_WRITE = "application.owner.write"

# Security Intelligence F1 (Advanced)
PERM_SECURITY_INTELLIGENCE_READ = "security_intelligence.read"
PERM_SECURITY_INTELLIGENCE_WRITE = "security_intelligence.write"

# Users
PERM_USER_READ = "users.read"
PERM_USER_INVITE = "users.invite"
PERM_USER_UPDATE = "users.update"
PERM_USER_DISABLE = "users.disable"
PERM_USER_DELETE = "users.delete"

# Teams
PERM_TEAM_READ = "teams.read"
PERM_TEAM_MANAGE = "teams.manage"

# Audit
PERM_AUDIT_READ = "audit.read"

# Scanner Control
PERM_SCANNER_READ = "scanners.read"
PERM_SCANNER_MANAGE = "scanners.manage"
PERM_SCANNER_UPGRADE = "scanners.upgrade"
PERM_SCANNER_ROLLBACK = "scanners.rollback"

# Administration
PERM_ORG_MANAGE = "organization.manage"
PERM_ORG_READ = "organization.read"
PERM_ORG_UPDATE = "organization.update"
PERM_ORG_MANAGE_MEMBERS = "organization.manage_members"
PERM_PROJECT_MANAGE = "project.manage"
PERM_POLICY_MANAGE = "policies.manage"

# Legacy aliases (for backward compat, map to new)
PERM_DASHBOARD_READ = "dashboard.read"
PERM_INGESTION_CREATE = "ingestion.create"
PERM_FINDING_READ = PERM_FINDING_READ
PERM_FINDING_TRIAGE = PERM_FINDING_TRIAGE

ALL_PERMISSIONS = {
    PERM_PROJECT_READ, PERM_PROJECT_CREATE, PERM_PROJECT_UPDATE, PERM_PROJECT_DELETE, PERM_PROJECT_MANAGE_MEMBERS,
    PERM_TARGET_READ, PERM_TARGET_CREATE, PERM_TARGET_UPDATE, PERM_TARGET_DELETE,
    PERM_SCAN_READ, PERM_SCAN_CREATE, PERM_SCAN_CANCEL, PERM_SCAN_DELETE,
    PERM_FINDING_READ, PERM_FINDING_TRIAGE, PERM_FINDING_ASSIGN, PERM_FINDING_UPDATE, PERM_FINDING_ACCEPT_RISK, PERM_FINDING_CLOSE, PERM_FINDING_REOPEN,
    PERM_ASSET_READ, PERM_ASSET_UPDATE, PERM_ATTACK_SURFACE_READ,
    PERM_MONITORING_READ, PERM_MONITORING_MANAGE,
    PERM_REPORT_READ, PERM_REPORT_CREATE, PERM_REPORT_DELETE,
    PERM_COMPLIANCE_READ, PERM_COMPLIANCE_MANAGE,
    PERM_CODE_SECURITY_READ, PERM_CODE_SECURITY_MANAGE,
    PERM_CLOUD_READ, PERM_CLOUD_MANAGE, PERM_CLOUD_SECURITY_READ, PERM_CLOUD_SECURITY_MANAGE,
    PERM_DAST_READ, PERM_DAST_MANAGE,
    PERM_REPO_READ, PERM_REPO_CONNECT, PERM_REPO_MANAGE,
    PERM_INTEGRATION_READ, PERM_INTEGRATION_MANAGE,
    PERM_CLOUD_ACCOUNT_READ, PERM_CLOUD_ACCOUNT_CONNECT, PERM_CLOUD_ACCOUNT_MANAGE,
    PERM_USER_READ, PERM_USER_INVITE, PERM_USER_UPDATE, PERM_USER_DISABLE, PERM_USER_DELETE,
    PERM_TEAM_READ, PERM_TEAM_MANAGE,
    PERM_AUDIT_READ,
    PERM_SCANNER_READ, PERM_SCANNER_MANAGE, PERM_SCANNER_UPGRADE, PERM_SCANNER_ROLLBACK,
    PERM_ORG_MANAGE, PERM_ORG_READ, PERM_ORG_UPDATE, PERM_ORG_MANAGE_MEMBERS, PERM_PROJECT_MANAGE, PERM_POLICY_MANAGE,
    PERM_DASHBOARD_READ, PERM_INGESTION_CREATE,
    PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_SCOPE_WRITE, PERM_EXTERNAL_SCOPE_ENTRY_READ, PERM_EXTERNAL_SCOPE_ENTRY_WRITE,
    PERM_EXTERNAL_DISCOVERY_READ, PERM_EXTERNAL_DISCOVERY_RUN,
    PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_ASSET_REVIEW, PERM_EXTERNAL_ASSET_AUTHORIZE, PERM_EXTERNAL_ASSET_REJECT,
    PERM_APPLICATION_READ, PERM_APPLICATION_WRITE, PERM_APPLICATION_ASSET_LINK, PERM_APPLICATION_FINDING_READ, PERM_APPLICATION_INVESTIGATION_CREATE, PERM_APPLICATION_OWNER_WRITE,
    PERM_SECURITY_INTELLIGENCE_READ, PERM_SECURITY_INTELLIGENCE_WRITE,
}

# ---------------------------------------------------------------------------
# Role -> permissions matrix (enterprise)
# ---------------------------------------------------------------------------

# Organization role permissions (canonical)
_ORG_ROLE_PERMISSIONS_CANONICAL: dict[str, set[str]] = {
    "organization_admin": {
        PERM_ORG_READ, PERM_ORG_UPDATE, PERM_ORG_MANAGE, PERM_ORG_MANAGE_MEMBERS,
        PERM_PROJECT_READ, PERM_PROJECT_CREATE, PERM_PROJECT_UPDATE, PERM_PROJECT_DELETE, PERM_PROJECT_MANAGE, PERM_PROJECT_MANAGE_MEMBERS,
        PERM_TARGET_READ, PERM_TARGET_CREATE, PERM_TARGET_UPDATE, PERM_TARGET_DELETE,
        PERM_SCAN_READ, PERM_SCAN_CREATE, PERM_SCAN_CANCEL, PERM_SCAN_DELETE,
        PERM_FINDING_READ, PERM_FINDING_TRIAGE, PERM_FINDING_ASSIGN, PERM_FINDING_UPDATE, PERM_FINDING_ACCEPT_RISK, PERM_FINDING_CLOSE, PERM_FINDING_REOPEN,
        PERM_ASSET_READ, PERM_ASSET_UPDATE, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ, PERM_MONITORING_MANAGE,
        PERM_REPORT_READ, PERM_REPORT_CREATE, PERM_REPORT_DELETE,
        PERM_COMPLIANCE_READ, PERM_COMPLIANCE_MANAGE,
        PERM_CODE_SECURITY_READ, PERM_CODE_SECURITY_MANAGE,
        PERM_CLOUD_READ, PERM_CLOUD_MANAGE, PERM_CLOUD_SECURITY_READ, PERM_CLOUD_SECURITY_MANAGE,
        PERM_DAST_READ, PERM_DAST_MANAGE,
        PERM_REPO_READ, PERM_REPO_CONNECT, PERM_REPO_MANAGE,
        PERM_INTEGRATION_READ, PERM_INTEGRATION_MANAGE,
        PERM_CLOUD_ACCOUNT_READ, PERM_CLOUD_ACCOUNT_CONNECT, PERM_CLOUD_ACCOUNT_MANAGE,
        PERM_USER_READ, PERM_USER_INVITE, PERM_USER_UPDATE, PERM_USER_DISABLE, PERM_USER_DELETE,
        PERM_TEAM_READ, PERM_TEAM_MANAGE,
        PERM_AUDIT_READ,
        PERM_SCANNER_READ, PERM_SCANNER_MANAGE, PERM_SCANNER_UPGRADE, PERM_SCANNER_ROLLBACK,
        PERM_POLICY_MANAGE,
        PERM_DASHBOARD_READ, PERM_INGESTION_CREATE,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_SCOPE_WRITE, PERM_EXTERNAL_SCOPE_ENTRY_READ, PERM_EXTERNAL_SCOPE_ENTRY_WRITE,
        PERM_EXTERNAL_DISCOVERY_READ, PERM_EXTERNAL_DISCOVERY_RUN,
        PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_ASSET_REVIEW, PERM_EXTERNAL_ASSET_AUTHORIZE, PERM_EXTERNAL_ASSET_REJECT,
        PERM_APPLICATION_READ, PERM_APPLICATION_WRITE, PERM_APPLICATION_ASSET_LINK, PERM_APPLICATION_FINDING_READ, PERM_APPLICATION_INVESTIGATION_CREATE, PERM_APPLICATION_OWNER_WRITE,
    },
    "security_admin": {
        PERM_ORG_READ,
        PERM_PROJECT_READ, PERM_PROJECT_CREATE, PERM_PROJECT_UPDATE, PERM_PROJECT_MANAGE_MEMBERS,
        PERM_TARGET_READ, PERM_TARGET_CREATE, PERM_TARGET_UPDATE, PERM_TARGET_DELETE,
        PERM_SCAN_READ, PERM_SCAN_CREATE, PERM_SCAN_CANCEL, PERM_SCAN_DELETE,
        PERM_FINDING_READ, PERM_FINDING_TRIAGE, PERM_FINDING_ASSIGN, PERM_FINDING_UPDATE, PERM_FINDING_ACCEPT_RISK, PERM_FINDING_CLOSE, PERM_FINDING_REOPEN,
        PERM_ASSET_READ, PERM_ASSET_UPDATE, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ, PERM_MONITORING_MANAGE,
        PERM_REPORT_READ, PERM_REPORT_CREATE, PERM_REPORT_DELETE,
        PERM_COMPLIANCE_READ, PERM_COMPLIANCE_MANAGE,
        PERM_CODE_SECURITY_READ, PERM_CODE_SECURITY_MANAGE,
        PERM_CLOUD_READ, PERM_CLOUD_MANAGE, PERM_CLOUD_SECURITY_READ, PERM_CLOUD_SECURITY_MANAGE,
        PERM_DAST_READ, PERM_DAST_MANAGE,
        PERM_REPO_READ, PERM_REPO_CONNECT, PERM_REPO_MANAGE,
        PERM_CLOUD_ACCOUNT_READ, PERM_CLOUD_ACCOUNT_CONNECT, PERM_CLOUD_ACCOUNT_MANAGE,
        PERM_USER_READ,
        PERM_TEAM_READ,
        PERM_AUDIT_READ,
        PERM_SCANNER_READ,
        PERM_DASHBOARD_READ, PERM_INGESTION_CREATE,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_SCOPE_WRITE, PERM_EXTERNAL_SCOPE_ENTRY_READ, PERM_EXTERNAL_SCOPE_ENTRY_WRITE,
        PERM_EXTERNAL_DISCOVERY_READ, PERM_EXTERNAL_DISCOVERY_RUN,
        PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_ASSET_REVIEW, PERM_EXTERNAL_ASSET_AUTHORIZE, PERM_EXTERNAL_ASSET_REJECT,
        PERM_APPLICATION_READ, PERM_APPLICATION_WRITE, PERM_APPLICATION_ASSET_LINK, PERM_APPLICATION_FINDING_READ, PERM_APPLICATION_INVESTIGATION_CREATE, PERM_APPLICATION_OWNER_WRITE,
    },
    "security_analyst": {
        PERM_ORG_READ,
        PERM_PROJECT_READ,
        PERM_TARGET_READ, PERM_TARGET_CREATE,
        PERM_SCAN_READ, PERM_SCAN_CREATE,
        PERM_FINDING_READ, PERM_FINDING_TRIAGE, PERM_FINDING_ASSIGN, PERM_FINDING_UPDATE,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ, PERM_MONITORING_MANAGE,
        PERM_REPORT_READ, PERM_REPORT_CREATE,
        PERM_COMPLIANCE_READ,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ, PERM_CLOUD_SECURITY_READ,
        PERM_DAST_READ,
        PERM_REPO_READ,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_USER_READ,
        PERM_TEAM_READ,
        PERM_AUDIT_READ,
        PERM_SCANNER_READ,
        PERM_DASHBOARD_READ, PERM_INGESTION_CREATE,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_SCOPE_ENTRY_READ, PERM_EXTERNAL_SCOPE_ENTRY_WRITE, PERM_EXTERNAL_DISCOVERY_READ, PERM_EXTERNAL_DISCOVERY_RUN,
        PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_ASSET_REVIEW, PERM_EXTERNAL_ASSET_AUTHORIZE, PERM_EXTERNAL_ASSET_REJECT,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ, PERM_APPLICATION_ASSET_LINK, PERM_APPLICATION_INVESTIGATION_CREATE,
    },
    "developer": {
        PERM_ORG_READ,
        PERM_PROJECT_READ,
        PERM_TARGET_READ,
        PERM_SCAN_READ,
        PERM_FINDING_READ, PERM_FINDING_UPDATE,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ,
        PERM_REPORT_READ,
        PERM_COMPLIANCE_READ,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ,
        PERM_DAST_READ,
        PERM_REPO_READ, PERM_REPO_CONNECT,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_USER_READ,
        PERM_TEAM_READ,
        PERM_SCANNER_READ,
        PERM_DASHBOARD_READ,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_DISCOVERY_READ,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ,
    },
    "viewer": {
        PERM_ORG_READ,
        PERM_PROJECT_READ,
        PERM_TARGET_READ,
        PERM_SCAN_READ,
        PERM_FINDING_READ,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ,
        PERM_REPORT_READ,
        PERM_COMPLIANCE_READ,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ, PERM_CLOUD_SECURITY_READ,
        PERM_DAST_READ,
        PERM_REPO_READ,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_USER_READ,
        PERM_TEAM_READ,
        PERM_AUDIT_READ,
        PERM_SCANNER_READ,
        PERM_DASHBOARD_READ,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_DISCOVERY_READ,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ,
    },
    "auditor": {
        PERM_ORG_READ,
        PERM_PROJECT_READ,
        PERM_TARGET_READ,
        PERM_SCAN_READ,
        PERM_FINDING_READ,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ,
        PERM_REPORT_READ,
        PERM_COMPLIANCE_READ, PERM_COMPLIANCE_MANAGE,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ, PERM_CLOUD_SECURITY_READ,
        PERM_DAST_READ,
        PERM_REPO_READ,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_USER_READ,
        PERM_TEAM_READ,
        PERM_AUDIT_READ,
        PERM_SCANNER_READ,
        PERM_DASHBOARD_READ,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_DISCOVERY_READ,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ,
    },
}

# Project role permissions (canonical)
_PROJECT_ROLE_PERMISSIONS_CANONICAL: dict[str, set[str]] = {
    "project_admin": {
        PERM_PROJECT_READ, PERM_PROJECT_UPDATE, PERM_PROJECT_DELETE, PERM_PROJECT_MANAGE, PERM_PROJECT_MANAGE_MEMBERS,
        PERM_TARGET_READ, PERM_TARGET_CREATE, PERM_TARGET_UPDATE, PERM_TARGET_DELETE,
        PERM_SCAN_READ, PERM_SCAN_CREATE, PERM_SCAN_CANCEL, PERM_SCAN_DELETE,
        PERM_FINDING_READ, PERM_FINDING_TRIAGE, PERM_FINDING_ASSIGN, PERM_FINDING_UPDATE, PERM_FINDING_ACCEPT_RISK, PERM_FINDING_CLOSE, PERM_FINDING_REOPEN,
        PERM_ASSET_READ, PERM_ASSET_UPDATE, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ, PERM_MONITORING_MANAGE,
        PERM_REPORT_READ, PERM_REPORT_CREATE, PERM_REPORT_DELETE,
        PERM_COMPLIANCE_READ, PERM_COMPLIANCE_MANAGE,
        PERM_CODE_SECURITY_READ, PERM_CODE_SECURITY_MANAGE,
        PERM_CLOUD_READ, PERM_CLOUD_MANAGE, PERM_CLOUD_SECURITY_READ, PERM_CLOUD_SECURITY_MANAGE,
        PERM_DAST_READ, PERM_DAST_MANAGE,
        PERM_REPO_READ, PERM_REPO_CONNECT, PERM_REPO_MANAGE,
        PERM_CLOUD_ACCOUNT_READ, PERM_CLOUD_ACCOUNT_CONNECT, PERM_CLOUD_ACCOUNT_MANAGE,
        PERM_USER_READ,
        PERM_TEAM_READ,
        PERM_AUDIT_READ,
        PERM_SCANNER_READ,
        PERM_DASHBOARD_READ, PERM_INGESTION_CREATE,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_SCOPE_WRITE, PERM_EXTERNAL_SCOPE_ENTRY_READ, PERM_EXTERNAL_SCOPE_ENTRY_WRITE,
        PERM_EXTERNAL_DISCOVERY_READ, PERM_EXTERNAL_DISCOVERY_RUN,
        PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_ASSET_REVIEW, PERM_EXTERNAL_ASSET_AUTHORIZE, PERM_EXTERNAL_ASSET_REJECT,
        PERM_APPLICATION_READ, PERM_APPLICATION_WRITE, PERM_APPLICATION_ASSET_LINK, PERM_APPLICATION_FINDING_READ, PERM_APPLICATION_INVESTIGATION_CREATE, PERM_APPLICATION_OWNER_WRITE,
    },
    "security_admin": {
        PERM_PROJECT_READ, PERM_PROJECT_UPDATE,
        PERM_TARGET_READ, PERM_TARGET_CREATE, PERM_TARGET_UPDATE, PERM_TARGET_DELETE,
        PERM_SCAN_READ, PERM_SCAN_CREATE, PERM_SCAN_CANCEL,
        PERM_FINDING_READ, PERM_FINDING_TRIAGE, PERM_FINDING_ASSIGN, PERM_FINDING_UPDATE, PERM_FINDING_ACCEPT_RISK, PERM_FINDING_CLOSE, PERM_FINDING_REOPEN,
        PERM_ASSET_READ, PERM_ASSET_UPDATE, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ, PERM_MONITORING_MANAGE,
        PERM_REPORT_READ, PERM_REPORT_CREATE,
        PERM_COMPLIANCE_READ, PERM_COMPLIANCE_MANAGE,
        PERM_CODE_SECURITY_READ, PERM_CODE_SECURITY_MANAGE,
        PERM_CLOUD_READ, PERM_CLOUD_MANAGE, PERM_CLOUD_SECURITY_READ, PERM_CLOUD_SECURITY_MANAGE,
        PERM_DAST_READ, PERM_DAST_MANAGE,
        PERM_REPO_READ, PERM_REPO_CONNECT, PERM_REPO_MANAGE,
        PERM_CLOUD_ACCOUNT_READ, PERM_CLOUD_ACCOUNT_CONNECT, PERM_CLOUD_ACCOUNT_MANAGE,
        PERM_DASHBOARD_READ, PERM_INGESTION_CREATE,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_SCOPE_WRITE, PERM_EXTERNAL_SCOPE_ENTRY_READ, PERM_EXTERNAL_SCOPE_ENTRY_WRITE,
        PERM_EXTERNAL_DISCOVERY_READ, PERM_EXTERNAL_DISCOVERY_RUN,
        PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_ASSET_REVIEW, PERM_EXTERNAL_ASSET_AUTHORIZE, PERM_EXTERNAL_ASSET_REJECT,
        PERM_APPLICATION_READ, PERM_APPLICATION_WRITE, PERM_APPLICATION_ASSET_LINK, PERM_APPLICATION_FINDING_READ, PERM_APPLICATION_INVESTIGATION_CREATE, PERM_APPLICATION_OWNER_WRITE,
    },
    "security_analyst": {
        PERM_PROJECT_READ,
        PERM_TARGET_READ, PERM_TARGET_CREATE,
        PERM_SCAN_READ, PERM_SCAN_CREATE,
        PERM_FINDING_READ, PERM_FINDING_TRIAGE, PERM_FINDING_ASSIGN, PERM_FINDING_UPDATE,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ, PERM_MONITORING_MANAGE,
        PERM_REPORT_READ, PERM_REPORT_CREATE,
        PERM_COMPLIANCE_READ,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ, PERM_CLOUD_SECURITY_READ,
        PERM_DAST_READ,
        PERM_REPO_READ,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_DASHBOARD_READ, PERM_INGESTION_CREATE,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_SCOPE_ENTRY_READ, PERM_EXTERNAL_SCOPE_ENTRY_WRITE, PERM_EXTERNAL_DISCOVERY_READ, PERM_EXTERNAL_DISCOVERY_RUN,
        PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_ASSET_REVIEW, PERM_EXTERNAL_ASSET_AUTHORIZE, PERM_EXTERNAL_ASSET_REJECT,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ, PERM_APPLICATION_ASSET_LINK, PERM_APPLICATION_INVESTIGATION_CREATE,
    },
    "developer": {
        PERM_PROJECT_READ,
        PERM_TARGET_READ,
        PERM_SCAN_READ,
        PERM_FINDING_READ, PERM_FINDING_UPDATE,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ,
        PERM_REPORT_READ,
        PERM_COMPLIANCE_READ,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ,
        PERM_DAST_READ,
        PERM_REPO_READ, PERM_REPO_CONNECT,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_DASHBOARD_READ,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_DISCOVERY_READ,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ,
    },
    "viewer": {
        PERM_PROJECT_READ,
        PERM_TARGET_READ,
        PERM_SCAN_READ,
        PERM_FINDING_READ,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ,
        PERM_REPORT_READ,
        PERM_COMPLIANCE_READ,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ, PERM_CLOUD_SECURITY_READ,
        PERM_DAST_READ,
        PERM_REPO_READ,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_DASHBOARD_READ,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_DISCOVERY_READ,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ,
    },
    "auditor": {
        PERM_PROJECT_READ,
        PERM_TARGET_READ,
        PERM_SCAN_READ,
        PERM_FINDING_READ,
        PERM_ASSET_READ, PERM_ATTACK_SURFACE_READ,
        PERM_MONITORING_READ,
        PERM_REPORT_READ,
        PERM_COMPLIANCE_READ,
        PERM_CODE_SECURITY_READ,
        PERM_CLOUD_READ, PERM_CLOUD_SECURITY_READ,
        PERM_DAST_READ,
        PERM_REPO_READ,
        PERM_CLOUD_ACCOUNT_READ,
        PERM_AUDIT_READ,
        PERM_DASHBOARD_READ,
        PERM_EXTERNAL_SCOPE_READ, PERM_EXTERNAL_ASSET_READ, PERM_EXTERNAL_DISCOVERY_READ,
        PERM_APPLICATION_READ, PERM_APPLICATION_FINDING_READ,
    },
}

# F1: security intelligence permissions — add to canonical roles
for _r in ("organization_admin", "security_admin"):
    _ORG_ROLE_PERMISSIONS_CANONICAL[_r].update({PERM_SECURITY_INTELLIGENCE_READ, PERM_SECURITY_INTELLIGENCE_WRITE})
for _r in ("project_admin", "security_admin"):
    _PROJECT_ROLE_PERMISSIONS_CANONICAL[_r].update({PERM_SECURITY_INTELLIGENCE_READ, PERM_SECURITY_INTELLIGENCE_WRITE})
for _r in ("security_analyst",):
    _ORG_ROLE_PERMISSIONS_CANONICAL[_r].update({PERM_SECURITY_INTELLIGENCE_READ, PERM_SECURITY_INTELLIGENCE_WRITE})
    _PROJECT_ROLE_PERMISSIONS_CANONICAL[_r].update({PERM_SECURITY_INTELLIGENCE_READ, PERM_SECURITY_INTELLIGENCE_WRITE})
for _r in ("developer", "viewer", "auditor"):
    _ORG_ROLE_PERMISSIONS_CANONICAL[_r].add(PERM_SECURITY_INTELLIGENCE_READ)
    _PROJECT_ROLE_PERMISSIONS_CANONICAL[_r].add(PERM_SECURITY_INTELLIGENCE_READ)

# Expose with legacy aliases for backward compat
ORG_ROLE_PERMISSIONS: dict[str, set[str]] = {}
for _k, _v in _ORG_ROLE_PERMISSIONS_CANONICAL.items():
    ORG_ROLE_PERMISSIONS[_k] = set(_v)
# Legacy aliases
ORG_ROLE_PERMISSIONS["member"] = set(ORG_ROLE_PERMISSIONS["viewer"])
ORG_ROLE_PERMISSIONS["org_admin"] = set(ORG_ROLE_PERMISSIONS["organization_admin"])

PROJECT_ROLE_PERMISSIONS: dict[str, set[str]] = {}
for _k, _v in _PROJECT_ROLE_PERMISSIONS_CANONICAL.items():
    PROJECT_ROLE_PERMISSIONS[_k] = set(_v)
PROJECT_ROLE_PERMISSIONS["analyst"] = set(PROJECT_ROLE_PERMISSIONS["security_analyst"])
PROJECT_ROLE_PERMISSIONS["project_admin"] = set(PROJECT_ROLE_PERMISSIONS["project_admin"])  # already

# Platform super_admin has all
SUPER_ADMIN_PERMISSIONS = set(ALL_PERMISSIONS)

def permissions_for_org_role(role: str) -> set[str]:
    return set(ORG_ROLE_PERMISSIONS.get(canonical_org_role(role), set()))

def permissions_for_project_role(role: str) -> set[str]:
    return set(PROJECT_ROLE_PERMISSIONS.get(canonical_project_role(role), set()))

def is_valid_org_role(role: str) -> bool:
    return role in ORG_ROLES

def is_valid_project_role(role: str) -> bool:
    return role in PROJECT_ROLES

def is_org_admin_role(role: str | None) -> bool:
    return role in ("org_admin", "organization_admin")
